# Generated by Django 3.0.6 on 2021-04-12 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_detail_dict_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='dict_item',
            field=models.TextField(),
        ),
    ]
