# Generated by Django 3.0.6 on 2021-04-12 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210412_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='username',
        ),
    ]
