# Generated by Django 3.0.6 on 2021-04-12 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_detail_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='username',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
