# Generated by Django 3.1 on 2021-05-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210417_2046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-ordered_date']},
        ),
        migrations.AddField(
            model_name='order',
            name='item_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
