# Generated by Django 3.1 on 2021-05-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210522_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='stars',
            field=models.DecimalField(decimal_places=2, default=3.5, max_digits=5),
        ),
    ]
